### ISSUE TITLE
Results on CIFAR10(Fig 16 in appendix)

### ISSUE THREAD

**Issue by alirezaabdollahpour** [mlfoundations/wise-ft#16]
Hi, Thanks for nice work ;)
How could you evaluate CLIP on CIFAR10 which was optimized for ImageNet?
particularly Fig. 16 in the paper's appendix.

**Comment by gabrielilharco** [comment]
Thanks @alirezaabdollahpour! In Figure 16 each subplot corresponds to a different model, each fine-tuned separately on a dataset. E.g. in the CIFAR10 plot, we show the interpolation between the zero-shot model and the model fine-tuned on CIFAR10, so there is no optimization on ImageNet there

**Comment by alirezaabdollahpour** [comment]
Thanks, @gabrielilharco . Could you share your **CIFAR10 and CIFAR100 checkpoints?**
And do you believe that the scenario in which _**we trained a model on ImageNet and evaluated it on CIFAR10 as OOD is feasible?**_

**Comment by gabrielilharco** [comment]
It's possible, a simple way to do this with CLIP models is to keep the classification layer frozen during fine-tuning, so you can keep using classification heads from any datasets. We have support for this in our other codebase https://github.com/mlfoundations/patching, and discuss more details in the paper (https://arxiv.org/abs/2208.05592). I don't have checkpoints for those datasets immediately available, but it should be fairly fast to fine-tune (a few minutes) using that codebase. CIFAR10 and CIFAR100 are both supported there.

**Comment by alirezaabdollahpour** [comment]
Thanks @gabrielilharco .
