### ISSUE TITLE
ModuleNotFoundError when running wise-ft.py on google colab

### ISSUE THREAD

**Issue by hzpro1221** [mlfoundations/wise-ft#19]
Hi, I'm getting ModuleNotFoundError when running wise-ft on google colab. I tried many solution i found in the internet but none of them working.
 After cloning your repo, I run this code
```
!python src/wise_ft.py   \
    --eval-datasets=ImageNet,ImageNetV2,ImageNetR,ImageNetA,ImageNetSketch  \
    --load=models/zeroshot.pt,models/finetuned.pt  \
    --results-db=results.jsonl  \
    --save=models/wiseft  \
    --data-location=~/data \
    --alpha 0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0
```
And got this error
`Traceback (most recent call last):
  File "/content/wise-ft/src/wise_ft.py", line 7, in <module>
    from src.models.eval import evaluate
ModuleNotFoundError: No module named 'src'`

**Comment by mitchellnw** [comment]
Hi, can you try running `export PYTHONPATH=$PWD` from the directory with `src` in it?

**Comment by hzpro1221** [comment]
Thank you for your helping. I've found the problem lead to this issue. `export` doesn't work in google colab. Howerver, this syntax working:
`import os`
`os.environ['PYTHONPATH'] += ":/content/wise-ft"`
