### ISSUE TITLE
Training Parameters

### ISSUE THREAD

**Issue by deadpipe** [mlfoundations/wise-ft#24]
Hello

Can you please tell what do Data(t) and Batch(t) mean when training from scratch using ViT-B/32:

![image](https://github.com/mlfoundations/wise-ft/assets/142412134/af66f9ea-40f3-417f-a2fd-24eb2a49bdce)

**Comment by gabrielilharco** [comment]
Hi @deadpipe, those are the times it takes for loading the data and processing a batch, in seconds

**Comment by deadpipe** [comment]
Thankyou!
