### ISSUE TITLE
Finetuning configs for more models

### ISSUE THREAD

**Issue by vtddggg** [mlfoundations/wise-ft#6]
Hi, dear authors. 
In this code you have provided an example for finetuning ViT-B/32:
```bash
python src/wise_ft.py   \
    --train-dataset=ImageNet  \
    --epochs=10  \
    --lr=0.00003  \
    --batch-size=512  \
    --cache-dir=cache  \
    --model=ViT-B/32  \
    --eval-datasets=ImageNet,ImageNetV2,ImageNetR,ImageNetA,ImageNetSketch  \
    --template=openai_imagenet_template  \
    --results-db=results.jsonl  \
    --save=models/wiseft/ViTB32  \
    --data-location=~/data \
    --alpha 0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0
``` 

By runing it, I can get the final WISE-FT results at \alpha=0.5 below:
```
ImageNet Top-1 accuracy: 0.7554
ImageNetR Top-1 accuracy: 0.7145
ImageNetA Top-1 accuracy: 0.3452
ImageNetSketch Top-1 accuracy: 0.4696
```

- Is the result correctly aligned with your results? Since I cannot find official results for ViT-B/32 in paper, I just want to ensure that I run the code correctly.
- What hyper-parameter config for other models, such as ViT-L, ViT-B, etc?

**Comment by mitchellnw** [comment]
Unfortunately I don't have the results for B/32 on hand, but that does seem reasonable. If you replace B/32 with B/16 it should match the plots produced in the repository (and should match the models that you can download with this repository). No further hyperparameter changes are needed.
