### ISSUE TITLE
Model Interpolation of Models of Different Size (#layers, hidden_size, intermediate_size, attention_head) 

### ISSUE THREAD

**Issue by sanyalsunny111** [mlfoundations/wise-ft#7]
I am trying to add two model checkpoints [ViT-B16 transformer] of different no. of layers, hidden size, attention heads and intermediate size using the same model interpolation way shown in the paper. Could you provide/suggest a minimal sample code or pseudo code for this as the way shown in the paper just works for the same models?

**Comment by mitchellnw** [comment]
Unfortunately in the paper we only interpolate models which have the same architecture. We currently don't know how to interpolate models with different architectures. If you end up trying out some ideas we would be very curious to hear the result! If the models are both vit b/16s, why do they have different architectures?

**Comment by sanyalsunny111** [comment]
Thank you for replying, Sure I am also curious to see how model interpolation works with different model config, will share my results if I succeed. I meant my zeroshot model is ViT B-16 and I have two smaller models with different config namely ViTB-16-tiny and ViTB-16-xtra-tiny by changing the #layers, hidden size and intermediate sizes.

**Comment by mitchellnw** [comment]
Best of luck! Hope you make this work as that would be very exciting.
