### ISSUE TITLE
zero-shot model

### ISSUE THREAD

**Issue by LindgeW** [mlfoundations/wise-ft#8]
Hi,

I would like to use the WiSE-FT method to other tasks or pretrained models (e.g., bert, gpt). In this context, the so-called `zero-shot model`  is actually the orignial model without fine-tuning, right? and the zero-model parameters actually means the directly-loaded pretrained parameters?

Thank you!

**Comment by LindgeW** [comment]
That's to say, for any pretrained model (e.g., bert), zero-shot model parameters denotes the parameters before fine-tuning on specific task dataset. Right?

**Comment by gabrielilharco** [comment]
Yes, that's right! A couple of notes: if you-re fine-tuning encoder-only models like BERT, it is common create a new classification head before fine-tuning, which doesn't exist on the pre-trained model. If you do that, you can interpolate only the backbone parameters, and always use the trained classification head, as in [this paper](https://arxiv.org/abs/2111.09832). In this case, you might want to try fine-tuning only the new layer (freezing the backbone) for a few steps first, then fine-tune end-to-end. Alternatively, you could also fine-tune without introducing new parameters, as in [this paper](https://arxiv.org/abs/2203.05482) (see Appendix J.5).

**Comment by LindgeW** [comment]
good, thank you so much!
