### ISSUE TITLE
Question about Table. 2 in the paper

### ISSUE THREAD

**Issue by vtddggg** [mlfoundations/wise-ft#9]
![image](https://user-images.githubusercontent.com/27721248/199229902-4ffd80ac-2790-4680-a360-ddcec08508ad.png)

How can we get the results in above figure. Do we need to design text prompts for each task and use them to init the classification head?

I try to add the classification head with random init weights, but get poor results for WiSE-FT.

**Comment by gabrielilharco** [comment]
Hi @vtddggg, thanks for the interest in our work! We indeed initialize the classification head using text prompts. I recommend using the prompts from OpenAI (see [here](https://github.com/openai/CLIP/blob/main/data/prompts.md)).

**Comment by vtddggg** [comment]
Thank for your reply!
It has solved my question. Closed
